/*
If error occurs it will be much harder to find exactly where error occured,
so it will be better if we break the test into multiple 'it' blocks
*/
it("Raises x to the power n", function() {
    let x = 5;
  
    let result = x;
    assert.equal(pow(x, 1), result);
  
    result *= x;
    assert.equal(pow(x, 2), result);
  
    result *= x;
    assert.equal(pow(x, 3), result);
  });